apiVersion: v1
kind: Service
metadata:
  name: project3-api
spec:
  selector:
    service: project3-api
  ports:
  - name: "5050"
    protocol: TCP
    port: 5153
    targetPort: 5153

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: project3-api
  labels:
    service: project3-api
spec:
  replicas: 1
  selector:
    matchLabels:
      service: project3-api
  template:
    metadata:
      labels:
        service: project3-api
    spec:
      containers:
      - name: project3-api
        image: 532631478217.dkr.ecr.us-east-1.amazonaws.com/project3:latest
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /health_check
            port: 5153
          initialDelaySeconds: 5
          timeoutSeconds: 2
        readinessProbe:
          httpGet:
            path: "/readiness_check"
            port: 5153
          initialDelaySeconds: 5
          timeoutSeconds: 5
        envFrom:
          - secretRef:
              name: huyng5screct
          - configMapRef:
              name: huyng5configmap
      restartPolicy: Always
