apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-new-pv
spec:
  capacity:
    storage: 5Gi  
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: gp2
  hostPath:
    path: "/mnt/data"  
